---
title: "Git"
author: "Dookyung Kim"
date: "2018-06-30"
output:
  xaringan::moon_reader:
    css: "slides.css"
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
exclude: true

```{r, message=FALSE, warning=FALSE, include=FALSE}
options(
  htmltools.dir.version = FALSE, # for blogdown
  width = 80,
  tibble.width = 80
)

library(emo)
htmltools::tagList(rmarkdown::html_dependency_font_awesome())

library(magrittr)
```

---
class: middle

# VERSION CONTROL WITH RSTUDIO AND GITHUB



---
## table of content

Getting set up with Git and RStudio

1 Configure Git

Version control with RStudio and Git

1. Setting up a version controlled project in RStudio
2. Making changes
3. Setting up a remote repository on GitHub
4. Subsequent workflow
    -  Pull and push changes
    -  Create a new branch
    -  Make and push changes to a branch
    -  Pull request and merge changes
    
Summary

---
## GETTING SET UP WITH GIT AND RSTUDIO

시작전에 먼저 GitHub account를 만들고 Git을 설치

커맨드창 열기(terminal, cmd, Ctrl+Alt+T)

check version of you git

```
git version
```
---

### CONFIGURE GIT

After installing git, you need to tell it who you are. 
Open a terminal window or command prompt (see above) and type the following:

```
git config --global user.email "you@youremail.com"

git config --global user.name "Your Name"
```

On succesful completion, you should see no output from these commands. You can also configure git to use your preferred editor for commit messages:

```
# Mac or Linux:
git config --global core.editor nano

# Windows:
git config --global core.editor notepad
```

---
## VERSION CONTROL WITH RSTUDIO AND GIT

### SETTING UP A VERSION CONTROLLED PROJECT IN RSTUDIO

Create a new project in RStudio as follows:

-  File -> New Project -> New Directory. Then click on Empty Project
-  In the Create New Project screen, give your project a name, navigate to the directory you want to save your project in and make sure that Create a git repository is checked. Then click on Create Project.

In the Create New Project screen, give your project a name,navigate to the directory you want to save your project in and make sure that Create a git repository is checked. Then click on Create Project.


Two files are created in the otherwise empty project:

-  .gitignore – Specifies files that should be ignored by the version control system.
-  NewProject.Rproj – Configuration information for the RStudio project.

---
## Create R script

First open a new R script as follows:

-  File -> New File -> R Script

Then, in the new empty R script, type the following lines of code, and click on the Run button in the top right corner of you script.

```
data(cars)
plot(cars)
```

save your script 

---
## How to commit

The git version control pane is in the top right hand corner of RStudio. Find it and click on the Git tab. You’ll see a list of the files in your project directory.

Git will only keep track of modifications to files that it has been asked to manage, so you need to tell git which files to track.

Tick the Staged checkbox for each file.

All of your files are now staged, ready for you to record those changes as a commit. Each commit creates a snapshot of the project directory, allowing you to record the state of your project through time.

Click on Commit.

This will open a pane showing details of the commit. You need to specify a commit message in the right hand panel. 

Once you’ve typed a commit message, click on Commit.


A message displaying the output from git will be shown.


Click on Close and you are done.

---
## 2.2. MAKING CHANGES

Now we want to make some changes to our R script. 

```
plot(cars, col="red")
```

Save the script.

Now, click on the Git tab in RStudio. You’ll notice that there’s only one file listed, since RStudio only lists files that have changed in its git interface.

Click on the Staged checkbox to stage your change. Now click on Diff (next to Commit) to display a summary of what’s changed. Lines that have been added are green. Lines that have been removed are red.

Add a commit message and click on Commit.

In the Git tab of RStudio, click on Diff and then History. You’ll see that you can look through every commit you’ve ever made. This can be extremely useful for finding bugs or looking back to how your model looked a few months ago.

---
## 2.3. SETTING UP A REMOTE REPOSITORY ON GITHUB

Likely you’ll want to connect your local repository to a remote repository using a hosting service such as GitHub. Syncing your local repository to a remote means that your code is backed up. Also, the remote repository acts as a central store for your project, allowing you to share your work or to access it from another computer.

First, you need to create a GitHub repository to use as a remote. Log into GitHub and go to your profile page. On the Repositories tab, click New.

At the Create a new repository screen, give your repository a name and click Create Repository.

The next screen gives sets of git commands for use in various circumstances. Find the section labelled …or push an existing repository from the command line and copy the commands to the clipboard.

These commands tell git to set the remote repository for your local repository.

In RStudio, navigate to the Git tab and click on More -> Shell….

Paste the git commands into the shell and press Enter to execute them.

Confirm that the project has been uploaded to your GitHub repository.

---
### Readme

It is good practice to always add a README.md file to your repository. A README.md file describes your project and all the files that are in the repo. A good README.md file makes it easy for others (or the future you!) to use your code and reproduce your project.

You can create a README.md file from RSTudio or in GitHub. Today we will be using the second option.

From the page of your repository in GitHub click on Add a README.

Now write a short description of your project, something like this.


At the bottom of the page, you can now change the commit message and add a more detailed description of your changes if you like. For the purpose of this exercise the commit message “Create README.md” is good enough. Click on Commit new file.

--- 
## 2.4. SUBSEQUENT WORKFLOW

### 2.4.1. PULL AND PUSH CHANGES

When you start working on your local repository (e.g., files on your own computer), it is best to start by Pulling any new changes off of your remote repository (e.g., GitHub). Similarly, when you are finished working on them in your local repository (e.g., your computer) it is good to then Push them to the remote repository (e.g., GitHub). We will walk through this basic workflow that enables you to keep your local files in sync across multiple computers or when files may change because of someone else working on the project.

To start working on a project, Pull any new changes to update your local copy.

Now you can make changes on your own computer. When you are finished, to Push these changes to the remote repository (e.g., GitHub).

---
### 2.4.2. CREATE A NEW BRANCH

Branching is the way to work on different versions of a repository at one time. 
We use branches to experiment and make edits before committing them to master.

By default your repository has one branch named master which is considered to be the definitive branch.

When you create a branch off the master branch, you’re making a copy, or snapshot, of master as it was at that point in time. 

Go to your repository and click the drop down at the top of the file list that says branch: master. Type a branch name into the new branch text box. Select the blue Create branch box or hit “Enter” on your keyboard.

Now you have two branches, master and NewPlot. 


Next we’ll add our changes to the new branch.

Go back to your project in RStudio. In the Git tab, if you hover the mouse pointer over the master drop menu you will see a tooltip that says Switch branch. However, if you click on master and open the drop menu you will notice that the only branch present is master.

This is because we need to Pull the changes that we made to our online repo into our local copy of the project on our computer. In the Git tab click on Pull. You will receive a message that tells you about all the changes that you have made in your repo, in this case adding a README.md file and creating a new branch.

If you click on master again you will now see the new branch that you created. Click on it to switch from master to NewPlot so we can continue working on the new branch.

--- 
## 2.4.3. MAKE AND PUSH CHANGES TO A BRANCH

Now we can add a new plot to our script. Type the following code and then click Run.

```
boxplot(cars$speed)
```

Save your edited R script, click on the Staged box like you did before and click on Commit. In the Review changes page, write a commit message and click on Commit. Before you close the window, click on Push.

---
## 2.4.4. PULL REQUEST AND MERGE CHANGES

Now go back to your repo on GitHub. You will notice that at the top of all you files there is a new section that says: Your recently pushed branches:. The changes you made to your script have been pushed to your online copy of the project and are now in the branch NewPlot. In order to merge them into your master branch we need to create a pull request.


In the Open a pull request page click on Create pull request.


GitHub has now compared the two versions of your project that are in the two branches, master and NewPlot and it is telling us that there are no conflicts between the two versions.

Click on the button that says *Compare and pull request*.

Now it’s time to bring your changes together – merging your NewPlot branch into the master branch. Click the green Merge pull request button to merge the changes into master. Click Confirm merge. Go ahead and delete the branch, since its changes have been incorporated, with the Delete branch button in the purple box.


---
## 3. SUMMARY

Congratulations!

You now know how to set up a version controlled project with RStudio and GitHub and your computer will never be full of v1.R, v2.R etc again!

You have seen that the standard workflow loop for version control in RStudio is very quick and simple:

Create a new branch
Make your change
Stage your change
Commit
Push to GitHub
Create a pull request
Merge your changes
As well as this basic workflow, you’ve learned how to look at changes using Diff and to inspect your project’s history.

