---
title: "Install Git and Bash Shell in Window"
author: "Dookyung Kim"
date: "2018-05-06"
output:
  xaringan::moon_reader:
    css: "slides.css"
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

exclude: true

```{r, message=FALSE, warning=FALSE, include=FALSE}
options(
  htmltools.dir.version = FALSE, # for blogdown
  width=80
)

# library(emo)
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```

---
# Installing Git


Bash is a commonly-used shell that gives you the power to do simple tasks more quickly.

-  Download the Git for [Windows installer](https://gitforwindows.org/).

-  Run the installer and follow the steps bellow:
  -  Click on "Next".
  -  Click on "Next".
  -  Keep "Use Git from the Windows Command Prompt" selected and click on "Next". If you forgot to do this programs that you need for the workshop will not work properly. If this happens rerun the installer and select the appropriate option.
  -  Click on "Next".
  -  Keep "Checkout Windows-style, commit Unix-style line endings" selected and click on "Next".
  -  Keep "Use Windows' default console window" selected and click on "Next".
  -  Click on "Install".
  -  Click on "Finish".
  
  
If your "HOME" environment variable is not set (or you don't know what this is): Open command prompt (Open Start Menu then type cmd and press [Enter])
Type the following line into the command prompt window exactly as shown:
setx HOME "%USERPROFILE%"

Press [Enter], you should see SUCCESS: Specified value was saved.
Quit command prompt by typing exit then pressing [Enter]
This will provide you with both Git and Bash in the Git Bash program.

